### ISSUE TITLE
Layout becomes wonky on wide screens

### ISSUE THREAD

**Issue by Nedlinin** [codeforhuntsville/code4huntsville#3]
When using a relatively wide screen, the layout becomes horribly wonky.

Normal:
![capture](https://cloud.githubusercontent.com/assets/298264/7309883/b5b26d52-e9e9-11e4-8800-b306a788a6d1.PNG)

Wide:
![captur3e](https://cloud.githubusercontent.com/assets/298264/7309885/bb98c9dc-e9e9-11e4-9dd9-a4f61df9204b.PNG)

**Comment by Nedlinin** [comment]
Other minor issue with layout.  Generally the layout just has issues with resizing it appears.

![capture](https://cloud.githubusercontent.com/assets/298264/7309911/06d6bf6c-e9ea-11e4-9f39-cc4633135055.PNG)

**Comment by larrymason** [comment]
Yip you are right... I know where the problem is I'll get it fixed.

**Comment by larrymason** [comment]
fixed 5/2/2015
